# Generated by Django 4.1.12 on 2023-11-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusUser',
            fields=[
                ('username', models.CharField(max_length=20, unique=True)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('page_balance', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
