# Generated by Django 4.1.13 on 2023-12-04 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusUser',
            fields=[
                ('base_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('page_balance', models.PositiveIntegerField(default=100)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('status', models.BooleanField()),
                ('name', models.CharField(max_length=20)),
                ('ext', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
