# Generated by Django 4.1.13 on 2023-12-04 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('print_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('status', models.BooleanField(default=False)),
                ('ext', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PrintingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('campus_id', models.CharField(max_length=11)),
                ('file_name', models.CharField(max_length=200)),
                ('page_count', models.PositiveIntegerField()),
                ('sheet_type', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PrinterLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=20)),
                ('building_name', models.CharField(max_length=20)),
                ('floor', models.PositiveSmallIntegerField()),
                ('room_code', models.CharField(max_length=3)),
            ],
            options={
                'unique_together': {('campus', 'building_name', 'floor', 'room_code')},
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printing_app.printerlocation')),
            ],
        ),
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=20)),
                ('file_type', models.CharField(max_length=5)),
                ('file_hash', models.CharField(max_length=64)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print_auth.campususer')),
            ],
        ),
    ]
