enum MENU_FACILITY {
  LY_THUONG_KIET = "Lý Thường Kiệt",
  DI_AN = "Dĩ An",
}

enum MENU_BUILDING_CS2 {
  H1 = "Toà H1",
  H2 = "Toà H2",
  H3 = "Toà H3",
  H6 = "Toà H6",
}

enum MENU_BUILDING_CS1 {
  B1 = "Toà B1",
  B2 = "Toà B2",
  B5 = "Toà B5",
  C5 = "Toà C5",
  C6 = "Toà C6",
  A1 = "Toà A1",
}

enum MENU_ROOM {
  R_101 = "Phòng 101",
  R_201 = "Phòng 201",
  R_207 = "Phòng 207",
  R_304 = "Phòng 304",
  R_401 = "Phòng 401",
  R_502 = "Phòng 502",
  R_601 = "Phòng 601",
}

enum MENU_PAPER_SIZE {
  SIZE_A4 = "A4",
  SIZE_A3 = "A3",
}

enum MENU_PRINT_TYPE {
  DOUBLE = "In hai mặt",
  ONE = "In một mặt",
}

enum MENU_NUMBER_OF_COPY {
  NONE = "Không in bản sao",
  TWO = "2 bản",
  FOUR = "4 bản",
  FIVE = "5 bản",
  CUSTOM = "Tùy chỉnh",
}

enum MENU_PRINT_PAGE {
  ALL = "Tất cả",
  ONLY_OLD = "Chỉ in các trang lẻ",
  ONLY_EVEN = "Chỉ in các trang chẵn",
  CUSTOM = "Tùy chỉnh",
}

enum ADMIN_MANAGEMENT_VIEW {
  EXTENSION_MANAGEMENT = "Quản Lý Đuôi File",
  ADD_PRINTER = "Thêm Máy In",
  PRINTER_MANAGEMENT = "Quản Lý Máy In",
  PRINTING_HISTORY = "Lịch Sử In",
  TRANSACTION_HISTORY = "Lịch Sử Giao Dịch",
}

enum SORT_CONFIG_PRINTER_MANAGEMENT {
  NAME_ASC = "SORT_CONFIG_PRINTER_MANAGEMENT_NAME_ASC",
  NAME_DESC = "SORT_CONFIG_PRINTER_MANAGEMENT_NAME_DESC",
  FACILITY_ASC = "SORT_CONFIG_PRINTER_MANAGEMENT_FACILITY_ASC",
  FACILITY_DESC = "SORT_CONFIG_PRINTER_MANAGEMENT_FACILITY_DESC",
  BUILDING_ASC = "SORT_CONFIG_PRINTER_MANAGEMENT_BUILDING_ASC",
  BUILDING_DESC = "SORT_CONFIG_PRINTER_MANAGEMENT_BUILDING_DESC",
  ROOM_ASC = "SORT_CONFIG_PRINTER_MANAGEMENT_ROOM_ASC",
  ROOM_DESC = "SORT_CONFIG_PRINTER_MANAGEMENT_ROOM_DESC",
}

enum SORT_CONFIG_EXTENSION_MANAGEMENT {
  NAME_ASC = "SORT_CONFIG_EXTENSION_MANAGEMENT_NAME_ASC",
  NAME_DESC = "SORT_CONFIG_EXTENSION_MANAGEMENT_NAME_DESC",
  EXTENSION_ASC = "SORT_CONFIG_EXTENSION_MANAGEMENT_EXTENSION_ASC",
  EXTENSION_DESC = "SORT_CONFIG_EXTENSION_MANAGEMENT_EXTENSION_DESC",
}

enum SORT_CONFIG_TRANSACTION_HISTORY {
  NAME_ASC = "SORT_CONFIG_TRANSACTION_HISTORY_NAME_ASC",
  NAME_DESC = "SORT_CONFIG_TRANSACTION_HISTORY_NAME_DESC",
  AMOUNT_ASC = "SORT_CONFIG_TRANSACTION_HISTORY_AMOUNT_ASC",
  AMOUNT_DESC = "SORT_CONFIG_TRANSACTION_HISTORY_AMOUNT_DESC",
  DATE_ASC = "SORT_CONFIG_TRANSACTION_HISTORY_DATE_ASC",
  DATE_DESC = "SORT_CONFIG_TRANSACTION_HISTORY_DATE_DESC",
}

enum HISTORY_TIME {
  A_WEEK_AGO = "Lịch sử 1 tuần",
  TWO_WEEKS_AGO = "Lịch sử 2 tuần",
  A_MONTH_AGO = "Lịch sử 1 tháng",
  THREE_MONTHS_AGO = "Lịch sử 3 tháng",
  SIX_MONTHS_AGO = "Lịch sử 6 tháng",
  ALL = "Tất cả",
}

export {
  MENU_FACILITY,
  MENU_BUILDING_CS1,
  MENU_BUILDING_CS2,
  MENU_ROOM,
  MENU_PAPER_SIZE,
  MENU_PRINT_TYPE,
  MENU_NUMBER_OF_COPY,
  MENU_PRINT_PAGE,
  ADMIN_MANAGEMENT_VIEW,
  SORT_CONFIG_PRINTER_MANAGEMENT,
  SORT_CONFIG_EXTENSION_MANAGEMENT,
  SORT_CONFIG_TRANSACTION_HISTORY,
  HISTORY_TIME,
};
