import { PrinterViewObject } from "../../../models/types";

const mockPrinterData: PrinterViewObject[] = [
  {
    id: "1",
    name: "Máy in H1",
    facility: "Dĩ An",
    building: "H1",
    room: "101",
    description: "This is a printer",
    isRunning: true,
  },
  {
    id: "2",
    name: "Máy in A1",
    facility: "Lý Thường Kiệt",
    building: "A1",
    room: "104",
    description: "This is a printer",
    isRunning: true,
  },
  {
    id: "3",
    name: "Máy in C5 Lầu 1",
    facility: "Lý Thường Kiệt",
    building: "C5",
    room: "107",
    description: "This is a printer",
    isRunning: false,
  },
  {
    id: "4",
    name: "Máy in B2",
    facility: "Lý Thường Kiệt",
    building: "B2",
    room: "402",
    description: "This is a printer",
    isRunning: true,
  },
  {
    id: "5",
    name: "Máy in C6",
    facility: "Lý Thường Kiệt",
    building: "C6",
    room: "201",
    description: "This is a printer",
    isRunning: true,
  },
  {
    id: "6",
    name: "Máy in H2",
    facility: "Dĩ An",
    building: "H2",
    room: "401",
    description: "This is a printer",
    isRunning: false,
  },
  {
    id: "7",
    name: "Máy in H3",
    facility: "Dĩ An",
    building: "H3",
    room: "101",
    description: "This is a printer",
    isRunning: true,
  },
  {
    id: "8",
    name: "Máy in H6",
    facility: "Dĩ An",
    building: "H6",
    room: "607",
    description: "This is a printer",
    isRunning: true,
  },
  {
    id: "9",
    name: "Máy in H6 Lầu 1",
    facility: "Dĩ An",
    building: "H6",
    room: "104",
    description: "This is a printer",
    isRunning: true,
  },
];

export { mockPrinterData };
