# Generated by Django 4.1.13 on 2023-12-04 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('a0_sheets', models.SmallIntegerField(default=0)),
                ('a1_sheets', models.SmallIntegerField(default=0)),
                ('a2_sheets', models.SmallIntegerField(default=0)),
                ('a3_sheets', models.SmallIntegerField(default=0)),
                ('a4_sheets', models.SmallIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total cost in USD')),
                ('status', models.CharField(default='INCOMPLETED', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
